<?php

return [
    'superadmin' => [
        ['label' => 'Dashboard', 'icon' => 'layout-dashboard', 'url' => '/manage', 'match' => 'manage'],
        ['section' => 'Keanggotaan'],
        ['label' => 'Calon Anggota', 'icon' => 'user-round-search', 'url' => '/manage/candidates', 'match' => 'manage/candidates*'],
        ['label' => 'Materi Mingguan Calon', 'icon' => 'book-open-check', 'url' => '/manage/candidate-topics', 'match' => 'manage/candidate-topics*'],
        ['label' => 'Data Anggota & NIA', 'icon' => 'users-round', 'url' => '/manage/members', 'match' => 'manage/members*'],
        ['label' => 'Tambah Anggota', 'icon' => 'user-plus', 'url' => '/manage/members/create', 'match' => 'manage/members/create'],
        ['section' => 'Publikasi'],
        ['label' => 'Artikel & Kegiatan', 'icon' => 'newspaper', 'url' => '/manage/contents', 'match' => 'manage/contents*'],
        ['label' => 'Tulis Artikel Baru', 'icon' => 'pen-line', 'url' => '/manage/contents/create', 'match' => 'manage/contents/create'],
        ['section' => 'Sistem & Web'],
        ['label' => 'Akun Pengguna', 'icon' => 'shield-check', 'url' => '/manage/users', 'match' => 'manage/users*'],
        ['label' => 'Sie Dokumentasi', 'icon' => 'camera', 'url' => '/manage/documentation-admin', 'match' => 'manage/documentation-admin*'],
        ['label' => 'Pengaturan Website', 'icon' => 'settings', 'url' => '/manage/settings', 'match' => 'manage/settings*'],
    ],
    'admin' => [
        ['label' => 'Dashboard', 'icon' => 'layout-dashboard', 'url' => '/manage', 'match' => 'manage'],
        ['section' => 'Keanggotaan'],
        ['label' => 'Calon Anggota', 'icon' => 'user-round-search', 'url' => '/manage/candidates', 'match' => 'manage/candidates*'],
        ['label' => 'Data Anggota & NIA', 'icon' => 'users-round', 'url' => '/manage/members', 'match' => 'manage/members*'],
        ['label' => 'Tambah Anggota', 'icon' => 'user-plus', 'url' => '/manage/members/create', 'match' => 'manage/members/create'],
        ['section' => 'Publikasi'],
        ['label' => 'Artikel & Kegiatan', 'icon' => 'newspaper', 'url' => '/manage/contents', 'match' => 'manage/contents*'],
        ['label' => 'Tulis Artikel Baru', 'icon' => 'pen-line', 'url' => '/manage/contents/create', 'match' => 'manage/contents/create'],
    ],
    'calon' => [
        ['label' => 'Dashboard', 'icon' => 'layout-dashboard', 'url' => '/candidate/dashboard', 'match' => 'candidate/dashboard*'],
        ['label' => 'Profil Saya', 'icon' => 'user-pen', 'url' => '/candidate/profile', 'match' => 'candidate/profile*'],
        ['section' => 'Kegiatan Calon'],
        ['label' => 'Kegiatan Mingguan', 'icon' => 'clipboard-pen-line', 'url' => '/candidate/weekly-log', 'match' => 'candidate/weekly-log*'],
        ['label' => 'Agenda Kegiatan', 'icon' => 'calendar-days', 'url' => '/candidate/agenda', 'match' => 'candidate/agenda*'],
        ['section' => 'Keamanan'],
        ['label' => 'Ganti Kata Sandi', 'icon' => 'key-round', 'url' => '/member/change-password', 'match' => 'member/change-password*'],
    ],
    'documentation' => [
        ['label' => 'Dashboard Dokumentasi', 'icon' => 'layout-dashboard', 'url' => '/manage', 'match' => 'manage'],
        ['section' => 'Publikasi & Keanggotaan'],
        ['label' => 'Artikel & Kegiatan', 'icon' => 'newspaper', 'url' => '/manage/contents', 'match' => 'manage/contents*'],
        ['label' => 'Calon Anggota', 'icon' => 'user-round-search', 'url' => '/manage/candidates', 'match' => 'manage/candidates*'],
        ['label' => 'Materi Mingguan Calon', 'icon' => 'book-open-check', 'url' => '/manage/candidate-topics', 'match' => 'manage/candidate-topics*'],
        ['label' => 'Data Anggota & NIA', 'icon' => 'users-round', 'url' => '/manage/members', 'match' => 'manage/members*'],
        ['label' => 'Tambah Anggota', 'icon' => 'user-plus', 'url' => '/manage/members/create', 'match' => 'manage/members/create'],
        ['section' => 'Portal Saya'],
        ['label' => 'Portal Saya', 'icon' => 'layout-dashboard', 'url' => '/member/dashboard', 'match' => 'member/dashboard*'],
        ['label' => 'Ubah Data & Kontak', 'icon' => 'user-pen', 'url' => '/member/profile', 'match' => 'member/profile*'],
        ['label' => 'Ganti Kata Sandi', 'icon' => 'key-round', 'url' => '/member/change-password', 'match' => 'member/change-password*'],
    ],
    'anggota' => [
        ['label' => 'Portal Saya', 'icon' => 'layout-dashboard', 'url' => '/member/dashboard', 'match' => 'member/dashboard*'],
        ['section' => 'Keanggotaan'],
        ['label' => 'Kartu Anggota (KTA)', 'icon' => 'id-card', 'url' => '/member/kta', 'match' => 'member/kta*'],
        ['label' => 'Ubah Data & Kontak', 'icon' => 'user-pen', 'url' => '/member/profile', 'match' => 'member/profile*'],
        ['section' => 'Publikasi'],
        ['label' => 'Artikel & Kegiatan Saya', 'icon' => 'newspaper', 'url' => '/member/contents', 'match' => 'member/contents*'],
        ['section' => 'Keamanan'],
        ['label' => 'Ganti Kata Sandi', 'icon' => 'key-round', 'url' => '/member/change-password', 'match' => 'member/change-password*'],
    ],
];
